name: Compile LaTeX Dissertation
on: [push, pull_request]
jobs:
  build_latex:
    name: Compile Dissertation
    runs-on: ubuntu-latest
    uses: hspaans/latexmk-action@v1.0.6
    with:
    # File format to generate
      format: -pdf 
    # Source file name
      filename: dissertation/l4proj.tex
