name: Compile LaTeX Dissertation
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Compile LaTex Document
        uses: fudan-mse/latex-action@v0.0.1
        with:
          # The root LaTeX file to be compiled
          root_file: dissertation/l4proj.tex
          # The working directory for the LaTeX engine
          working_directory: ..
          # The LaTeX engine to be invoked
          compiler: latexmk
          # Extra arguments to be passed to the LaTeX engine
          args: -pdf -file-line-error -interaction=nonstopmode
          # Install extra packages by tlmgr
          extra_packages: # optional
          # Install extra packages by apk
          extra_system_packages: # optional
