name: Compile LaTex Dissertation
on: 
  push:
    branches:
      - master
      - development
  pull_request:
    branches: 
      - master
      - development
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Latexmk
        uses: hspaans/latexmk-action@v1.0.6
        with:
          format: pdf
          filename: dissertation/l4proj.tex
