name: Test Python Code
on:
  push:
    branches:
       - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: pip install -r src/requirements.txt
    - name: Build and Run
      run: |
        python src/test/test_distances.py
